# Generated by Django 6.0.2 on 2026-03-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0007_alter_projectteam_members_alter_projectteam_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectclient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
