# Generated by Django 6.0.2 on 2026-03-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0011_alter_invoiceitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectclient',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='projectclient',
            name='pan_number',
        ),
        migrations.AddField(
            model_name='projectbusinessaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='projectbusinessaddress',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectbusinessaddress',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectbusinessaddress',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='projectbusinessaddress',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectbusinessaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
