# Generated by Django 6.0.2 on 2026-03-07 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0012_remove_projectclient_gst_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='djangosimplemissionapp.projectbusinessaddress'),
        ),
    ]
