# Generated by Django 6.0.2 on 2026-03-07 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0013_alter_invoice_client_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_base_information',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_business_address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_domain',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_excution',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_finance',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_server',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_service',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_team',
        ),
        migrations.RemoveField(
            model_name='projectservice',
            name='project_base_information',
        ),
        migrations.RemoveField(
            model_name='projectservice',
            name='project_excution',
        ),
        migrations.RemoveField(
            model_name='projectservice',
            name='project_finance',
        ),
        migrations.RemoveField(
            model_name='projectservice',
            name='project_team',
        ),
        migrations.RemoveField(
            model_name='projectservice',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectbaseinformation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_base_informations', to='djangosimplemissionapp.project'),
        ),
        migrations.AddField(
            model_name='projectbusinessaddress',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_business_addresses', to='djangosimplemissionapp.project'),
        ),
        migrations.AddField(
            model_name='projectclient',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_clients', to='djangosimplemissionapp.project'),
        ),
        migrations.AddField(
            model_name='projectdomain',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_domains', to='djangosimplemissionapp.project'),
        ),
        migrations.AddField(
            model_name='projectexcution',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_excutions', to='djangosimplemissionapp.project'),
        ),
        migrations.AddField(
            model_name='projectfinance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_finances', to='djangosimplemissionapp.project'),
        ),
        migrations.AddField(
            model_name='projectserver',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_servers', to='djangosimplemissionapp.project'),
        ),
        migrations.AddField(
            model_name='projectservice',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectservice',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectservice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='djangosimplemissionapp.project'),
        ),
        migrations.AddField(
            model_name='projectservice',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_teams', to='djangosimplemissionapp.project'),
        ),
        migrations.AddField(
            model_name='projectteammember',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_team_members', to='djangosimplemissionapp.project'),
        ),
        migrations.AlterField(
            model_name='projectbaseinformation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbaseinformation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='members',
            field=models.ManyToManyField(related_name='project_allocations', to='djangosimplemissionapp.projectteammember'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectServiceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('allocated_days', models.IntegerField(default=0)),
                ('actual_days', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='djangosimplemissionapp.projectservice')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectServiceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_days', models.IntegerField(default=0)),
                ('actual_days', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='djangosimplemissionapp.projectservice')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangosimplemissionapp.team')),
            ],
        ),
    ]
