# Generated by Django 6.0.2 on 2026-03-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0021_alter_activityexceedcomment_id_alter_activitylog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/'),
        ),
    ]
