# Generated by Django 5.2.5 on 2026-03-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0024_clientadvancepayment_remaining_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='advance_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ClientAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='djangosimplemissionapp.projectbusinessaddress')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangosimplemissionapp.payment')),
            ],
        ),
        migrations.CreateModel(
            name='ClientLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Invoice', 'Invoice'), ('Payment', 'Payment'), ('Advance', 'Advance'), ('Adjustment', 'Adjustment')], max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='djangosimplemissionapp.projectbusinessaddress')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangosimplemissionapp.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangosimplemissionapp.payment')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientAdvancePayment',
        ),
    ]
