# Generated by Django 5.2.5 on 2026-03-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0027_remove_payment_advance_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientledger',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='clientledger',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
