# Generated by Django 5.2.5 on 2026-03-10 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0030_remove_projectbusinessaddress_advance_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='advance_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_applications', to='djangosimplemissionapp.clientadvance'),
        ),
    ]
