# Generated by Django 5.2.5 on 2026-03-10 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0031_payment_advance_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientadvance',
            name='payment',
        ),
    ]
