# Generated by Django 5.2.5 on 2026-03-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0034_remove_clientledger_invoice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientLedger',
        ),
    ]
