# Generated by Django 5.2.5 on 2026-03-10 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0035_delete_clientledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbusinessaddress',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='business_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='djangosimplemissionapp.projectbusinessaddress'),
        ),
    ]
