# Generated by Django 5.2.5 on 2026-03-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0036_remove_projectbusinessaddress_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='business_address',
        ),
        migrations.AddField(
            model_name='projectbusinessaddress',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='project_business_addresses', to='djangosimplemissionapp.project'),
        ),
    ]
