# Generated by Django 5.2.5 on 2026-03-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0038_projectdomain_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedailyactivity',
            name='post_time',
        ),
        migrations.RemoveField(
            model_name='employeedailyactivity',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='employeedailyactivity',
            name='project_start_date',
        ),
        migrations.RemoveField(
            model_name='employeedailyactivity',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employeedailyactivity',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employeedailyactivity',
            name='hours_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employeedailyactivity',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedailyactivity',
            name='delay_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedailyactivity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employeedailyactivity',
            name='is_timeline_exceeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeedailyactivity',
            name='pending_work_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
