# Generated by Django 6.0.2 on 2026-03-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0041_alter_attendance_employee_alter_salary_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherincome',
            name='company',
        ),
    ]
