# Generated by Django 5.2.5 on 2026-03-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0045_projectdomain_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='working_days',
            field=models.IntegerField(default=26),
        ),
    ]
