# Generated by Django 5.2.5 on 2026-03-24 03:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0047_alter_attendance_options_attendance_late_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('working_days', models.IntegerField(default=26)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_salary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
