# Generated by Django 5.2.5 on 2026-03-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0048_usersalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='month',
        ),
        migrations.AddField(
            model_name='salary',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
