# Generated by Django 5.2.5 on 2026-03-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0049_remove_salary_month_salary_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersalary',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
