# Generated by Django 6.0.2 on 2026-03-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0053_projectteam_status_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectserviceteam',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progressing', 'Progressing'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
