# Generated by Django 5.2.5 on 2026-03-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0054_projectserviceteam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectserviceteam',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectserviceteam',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
