# Generated by Django 6.0.2 on 2026-03-31 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0059_projectteam_description_projectteam_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='project_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='djangosimplemissionapp.projectteam'),
        ),
    ]
