# Generated by Django 6.0.2 on 2026-04-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0066_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('view_teamperformance', 'Can view team performance analytics'), ('view_all_team_performance', 'Can view performance of all teams'), ('view_own_team_performance', 'Can view performance of own team only')]},
        ),
    ]
