# Generated by Django 5.2.5 on 2026-04-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0070_alter_employeedailyactivity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteammember',
            name='actual_days_spent',
            field=models.IntegerField(blank=True, default=0, help_text='Actually Spent Days', null=True),
        ),
    ]
