# Generated by Django 6.0.2 on 2026-03-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbusinessaddress',
            name='client',
        ),
    ]
