# Generated by Django 6.0.2 on 2026-03-04 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0006_alter_team_members_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteam',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_allocations', to='djangosimplemissionapp.projectteammember'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_allocations', to='djangosimplemissionapp.team'),
        ),
    ]
