# Generated by Django 6.0.2 on 2026-03-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0014_remove_project_project_base_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='expairy_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
