# Generated by Django 5.2.5 on 2026-03-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0016_remove_company_clients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='expairy_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='expairy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
