# Generated by Django 5.2.5 on 2026-03-09 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0022_alter_projectdocument_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='djangosimplemissionapp.projectbusinessaddress')),
            ],
        ),
    ]
