# Generated by Django 5.2.5 on 2026-03-09 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0023_clientadvancepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientadvancepayment',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='advance_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_payments', to='djangosimplemissionapp.clientadvancepayment'),
        ),
    ]
