# Generated by Django 5.2.5 on 2026-03-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0025_remove_payment_advance_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbusinessaddress',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
