# Generated by Django 5.2.5 on 2026-03-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0026_projectbusinessaddress_advance_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='advance_amount',
        ),
    ]
