# Generated by Django 5.2.5 on 2026-03-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0028_alter_clientledger_options_clientledger_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbusinessaddress',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
