# Generated by Django 5.2.5 on 2026-03-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0029_projectbusinessaddress_remaining_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbusinessaddress',
            name='advance_balance',
        ),
        migrations.RemoveField(
            model_name='projectbusinessaddress',
            name='remaining_amount',
        ),
        migrations.AddField(
            model_name='clientadvance',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='clientadvance',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
