# Generated by Django 5.2.5 on 2026-03-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0032_remove_clientadvance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientadvance',
            name='is_manual',
            field=models.BooleanField(default=True),
        ),
    ]
