# Generated by Django 5.2.5 on 2026-03-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0033_clientadvance_is_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientledger',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='clientledger',
            name='payment',
        ),
        migrations.AddField(
            model_name='clientadvance',
            name='initial_usage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
