# Generated by Django 6.0.2 on 2026-03-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0042_remove_otherincome_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherexpense',
            name='company',
        ),
    ]
