# Generated by Django 5.2.5 on 2026-03-12 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0043_remove_otherexpense_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='project_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='djangosimplemissionapp.projectdomain'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='project_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='djangosimplemissionapp.projectserver'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='project_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='djangosimplemissionapp.projectservice'),
        ),
    ]
