# Generated by Django 5.2.5 on 2026-03-12 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0044_invoiceitem_project_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdomain',
            name='client_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='djangosimplemissionapp.projectbusinessaddress'),
        ),
        migrations.AddField(
            model_name='projectserver',
            name='client_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='djangosimplemissionapp.projectbusinessaddress'),
        ),
        migrations.AddField(
            model_name='projectservice',
            name='client_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='djangosimplemissionapp.projectbusinessaddress'),
        ),
    ]
