# Generated by Django 5.2.5 on 2026-03-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0050_usersalary_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedailyactivity',
            name='target_work_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
