# Generated by Django 6.0.2 on 2026-03-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0051_employeedailyactivity_target_work_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectservicemember',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectservicemember',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectservicemember',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectservicemember',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
