# Generated by Django 6.0.2 on 2026-03-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0052_projectservicemember_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progressing', 'Progressing'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progressing', 'Progressing'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectservice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progressing', 'Progressing'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectservicemember',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progressing', 'Progressing'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectteammember',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progressing', 'Progressing'), ('Completed', 'Completed')], default='Pending', help_text='Task Status', max_length=50),
        ),
    ]
