# Generated by Django 6.0.2 on 2026-03-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0055_projectserviceteam_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectserviceteam',
            name='actual_days',
        ),
        migrations.RemoveField(
            model_name='projectserviceteam',
            name='allocated_days',
        ),
        migrations.RemoveField(
            model_name='projectteam',
            name='actual_time_spent',
        ),
        migrations.RemoveField(
            model_name='projectteam',
            name='allocated_time',
        ),
        migrations.AddField(
            model_name='projectserviceteam',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectserviceteam',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
