# Generated by Django 6.0.2 on 2026-03-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0057_projectservice_actual_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectservice',
            name='start_date',
        ),
    ]
