# Generated by Django 6.0.2 on 2026-04-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0062_remove_user_roles_role_permissions_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_dashboard', 'Can view analytical dashboard')]},
        ),
    ]
