# Generated by Django 6.0.2 on 2026-04-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0063_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_analytics', 'Can view analytical dashboard')]},
        ),
        migrations.AlterModelOptions(
            name='projectdomain',
            options={'permissions': [('view_domain_stats', 'Can view domain analytics and stats')]},
        ),
        migrations.AlterModelOptions(
            name='projectserver',
            options={'permissions': [('view_server_stats', 'Can view server analytics and stats')]},
        ),
    ]
