# Generated by Django 6.0.2 on 2026-04-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0064_alter_project_options_alter_projectdomain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_analytics', 'Can view analytical dashboard'), ('view_projectstats', 'Can view project analytics and stats')]},
        ),
    ]
