# Generated by Django 6.0.2 on 2026-04-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0065_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('view_teamperformance', 'Can view team performance analytics')]},
        ),
    ]
