# Generated by Django 6.0.2 on 2026-04-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0067_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('view_all_employee_performance', 'Can view all employees performance'), ('view_own_employee_performance', 'Can view own performance')]},
        ),
    ]
