# Generated by Django 6.0.2 on 2026-04-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0068_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_all_employee_performance', 'Can view all employee performance'), ('view_own_employee_performance', 'Can view own employee performance')]},
        ),
    ]
