# Generated by Django 6.0.2 on 2026-04-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0069_alter_role_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedailyactivity',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('view_all_activities', 'Can view all employee daily activities'), ('view_own_activities', 'Can view own daily activities')], 'verbose_name_plural': 'Employee Daily Activities'},
        ),
    ]
