# Generated by Django 5.2.5 on 2026-04-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0071_alter_projectteammember_actual_days_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='account_name',
            field=models.CharField(blank=True, default='Exmedia', max_length=200),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='account_number',
            field=models.CharField(blank=True, default='1234567890', max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='bank_name',
            field=models.CharField(blank=True, default='Federal Bank', max_length=200),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, default='FDRL0001234', max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='upi_id',
            field=models.CharField(blank=True, default='exmedia@upi', max_length=100),
        ),
    ]
