# Generated by Django 6.0.2 on 2026-04-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0073_notification_notification_type_notification_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdomain',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Expired', 'Expired')], default='Pending', max_length=50, null=True),
        ),
    ]
