# Generated by Django 6.0.2 on 2026-04-27 09:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0076_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('plan_category', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_active_date', models.DateField(blank=True, null=True)),
                ('plan_deactive_date', models.DateField(blank=True, null=True)),
                ('plan_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Expired', 'Expired')], default='Pending', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_exbots', to='djangosimplemissionapp.project')),
            ],
        ),
    ]
