# Generated by Django 6.0.2 on 2026-04-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0077_projectexbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='project_exbot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='djangosimplemissionapp.projectexbot'),
        ),
    ]
